//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KN_WEB.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tServicio
    {
        public int Consecutivo { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public decimal Precio { get; set; }
        public int Estado { get; set; }
        public string Imagen { get; set; }
    }
}
